version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_engineering
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data